codecov:
  require_ci_to_pass: false

coverage:
  status:
    project:
      default:
        target: 85%
        threshold: 1%
        informational: true
    patch:
      default:
        target: 90%
        threshold: 1%
        if_ci_failed: error
        informational: true

  range: 75..80     # First number represents red, and second represents green
                    # (default is 70..100)
  round: down       # up, down, or nearest
  precision: 2      # Number of decimal places, between 0 and 5
