codecov:
  require_ci_to_pass: false

coverage:
  range: 80..90
  round: down
  precision: 2
  status:
    project:
      default:
        target: 85%
        threshold: 1%
        informational: true
    patch:
      default:
        target: 90%
        threshold: 1%
        if_ci_failed: error
        informational: true
comment:
  layout: reach, diff, flags, files
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
